The following code is running on the CPU - without any optimizations:

In [1]:
def python_forloop_list_approach(x, w):
    z = 0.
    for i in range(len(x)):
        z += x[i] * w[i]
    return z


a = [1., 2., 3.]
b = [4., 5., 6.]

print(python_forloop_list_approach(a, b))

32.0


Let's benchmark the implementation with the %timeit function: 300 to 400 microseconds

In [2]:
large_a = list(range(10000))
large_b = list(range(10000))

%timeit python_forloop_list_approach(large_a, large_b)

390 μs ± 14.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Let's do everything with numpy: just a few microseconds

In [3]:
import numpy as np

def numpy_dotproduct_approach(x, w):
    # same as np.dot(x, w)
    # and same as x @ w
    return x.dot(w)

# Creates an array of numbers from 0 to 9999
large_a = np.arange(10000)
large_b = np.arange(10000)

%timeit numpy_dotproduct_approach(large_a, large_b)

3.22 μs ± 98.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# N-dimensional Arrays 

In [4]:
# One dimensional array
a = [1., 2., 3.]
array_1d = np.array(a)
print("Content: ", array_1d)
print("Data type:", array_1d.dtype)
print("Dimensions: ", array_1d.ndim)
print("Shape: ", array_1d.shape)
print("")

# Two dimensional array
entries =   [
                [4, 5, 6], 
                [7, 8, 9]
            ]
array_2d = np.array(entries)
print("Content: ", array_2d)
print("Data type: ", array_2d.dtype)
print("Dimensions: ", array_2d.ndim)
print("Shape: ", array_2d.shape)

Content:  [1. 2. 3.]
Data type: float64
Dimensions:  1
Shape:  (3,)

Content:  [[4 5 6]
 [7 8 9]]
Data type:  int64
Dimensions:  2
Shape:  (2, 3)


# Array Indexing

In [68]:
# The 1st and 3rd entry of the array
array = np.arange(10, 20)
print(array[0])
print(array[2])

# The first 3 entries of the array
print(array[0:3])

# The last 3 entries of the array
print(array[-3:])

# Two dimensional array
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array[0, -2])
print(array[0, -2:])
print(array[1, -2])
print(array[1, 0:3])

10
12
[10 11 12]
[17 18 19]
2
[2 3]
5
[4 5 6]


# Universal Functions

In [83]:
array = [[1, 2, 3], [4, 5, 6]] 

# An inefficient nested loop implementation
for row_index, row_value in enumerate(array):
    for col_index, col_value in enumerate(row_value):
        array[row_index][col_index] += 1

print(array)

# An efficient numpy implementation with a Universal Function (ufunc)
array = np.add(array, 1)
print(array)

# Or, with a simplified syntax
array += 7
print(array)

# Calculate the sum of all entries across the row axis
print(np.add.reduce(array, axis = 0))
print(array.sum(axis = 0))

# Calculate the sum of all entries across the column axis
print(np.add.reduce(array, axis = 1))
print(array.sum(axis = 1))


[[2, 3, 4], [5, 6, 7]]
[[3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]]
[23 25 27]
[23 25 27]
[33 42]
[33 42]


# Broadcasting

In [141]:
# Broadcasting a scalar value
array1 = np.array([1, 2, 3])
array1 += 1
print(array1)
print("")

# Broadcasting an array of the same shape
array1 += np.array([2, 2, 2])
print(array1)
print("")

# Broadcasting an array of a different shape
array2 = np.array([[4, 5, 6], [7, 8, 9]])
array3 = array1 + array2
print(array3)
print("")

[2 3 4]

[4 5 6]

[[ 8 10 12]
 [11 13 15]]



# Boolean Masks

In [91]:
array = np.array([[1, 2, 3], [4, 5, 6]])

greater_than4_mask = array > 4
print(greater_than4_mask)
print(array[greater_than4_mask])

[[False False False]
 [False  True  True]]
[5 6]


# Reshaping Arrays

In [104]:
array_1dim = np.array([1, 2, 3, 4, 5, 6])

# Create a 2-dimensional array with 2 rows and 3 columns
array_2dim = array_1dim.reshape(2, 3)
print(array_2dim)
print("")

# The number of rows are unspecified (-1), but the number of columns is 2
array_2dim = array_1dim.reshape(-1, 2)
print(array_2dim)
print("")

# Flatten the array to a 1-dimensional array
array_1dim = array_2dim.flatten()
print(array_1dim)
print("")

# Concatenate two arrays
array1 = np.array([1, 2, 3])
array2 = np.concatenate((array1, array1))
print(array2)
print("")

# Concatenate two arrays along the row axis
array1 = np.array([[1, 2, 3]])
array2 = np.concatenate((array1, array1), axis = 1)
print(array2)
print("")

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 2 3 1 2 3]

[[1 2 3 1 2 3]]



# Linear Algebra

In [6]:
row_vector = np.array([[1, 2, 3], 
                       [4, 5, 6]])
column_vector = np.array([1, 2, 3]).reshape(-1, 1)
print(row_vector)
print("")
print(column_vector)
print("")

# Matrix multiplication
# Number of columns on the left matrix must match the number of rows on the right matrix
# => 1 * 1 + 2 * 2 + 3 * 3 = 14
# => 4 * 1 + 5 * 2 + 6 * 3 = 32
print(np.matmul(row_vector, column_vector))
print(row_vector @ column_vector)
print("")

# Dot product, because both are 1-dimensional arrays
# => 1 * 4 + 2 * 5 + 3 * 6 = 32
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))
print(a @ b)
print("")

# Matrix multiplication, because both are 2-dimensional arrays
print(np.dot(row_vector, column_vector))
print(row_vector @ column_vector)
print("")

# Transpose a matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
transposed_matrix = np.transpose(matrix)
print(transposed_matrix)
transposed_matrix = transposed_matrix.T
print(transposed_matrix)
print("")

# [1, 2, 3] 
# [4, 5, 6]
#     *
#   [1, 4]
#   [2, 5]
#   [3, 6]

# => 1 * 1 + 2 * 2 + 3 * 3 = 14
# => 4 * 1 + 5 * 2 + 6 * 3 = 32
# => 1 * 4 + 2 * 5 + 3 * 6 = 32
# => 4 * 4 + 5 * 5 + 6 * 6 = 77
print(matrix.dot(matrix.transpose()))
print(matrix @ matrix.transpose())

[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]]

[[14]
 [32]]
[[14]
 [32]]

32
32

[[14]
 [32]]
[[14]
 [32]]

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]

[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


# Linear Equations

`2x + 3y = 5`  
`4x - y = 6`

In [5]:
# Input matrix
a = np.array([[2, 3], 
              [4, -1]])
b = np.array([5, 6])

# Solve the linear equation
result = np.linalg.solve(a, b)
print(result)

# Check the result
print(a @ result)

[1.64285714 0.57142857]
[5. 6.]


`x + 2y + 3z = 6`  
`2x -y + z = 4`  
`3x + y - 2z = 3`  

In [135]:
# Input matrix
a = np.array([[1, 2, 3], 
              [2, -1, 1],
              [3, 1, -2]])
b = np.array([6, 4, 3])

# Solve the Linear Equation
result = np.linalg.solve(a, b)
print(result)

# Check the result
print(a @ result)

[1.63333333 0.43333333 1.16666667]
[6. 4. 3.]


# Non Linear Equations

`x^3 - y = 4,`  
`ln(x) + y^2 = 3`  

In [139]:
from scipy.optimize import fsolve
import numpy as np

# Definition of the Non Linear Equation
def equations(vars):
    x, y = vars
    equation1 = x**3 - y - 4  # 1st equation: x^3 - y = 4
    equation2 = np.log(x) + y**2 - 3  # 2nd equation: ln(x) + y^2 = 3
    return [equation1, equation2]

# Initial values for x and y
initial_guess = [2, 1]

# Calculate the result
solution = fsolve(equations, initial_guess)

# Print the result
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")

x = 1.7713871014392015
y = 1.5582801696730748
