In [133]:
import numpy
import scipy.special

# Definition of a simple Neural Network
class NeuralNetwork:

    # Initializes the Neural Network
    def __init__(self, InputNodes, HiddenNodes, OutputNodes, LearningRate):
        self.InputNodes = InputNodes
        self.HiddenNodes = HiddenNodes
        self.OutputNodes = OutputNodes
        self.LearningRate = LearningRate

        # Use the Sigmoid function as the Activation Function
        self.activation_function = lambda x: scipy.special.expit(x)

        # Initialize the weights between the various layers (Input Layer => Hidden Layer => Output Layer)
        self.WeightsInputToHidden = (numpy.random.rand(self.HiddenNodes, self.InputNodes) - 0.5)
        self.WeightsHiddenToOutput = (numpy.random.rand(self.OutputNodes, self.HiddenNodes) - 0.5)
        pass

    # Trains the Neural Network
    def Train(self, InputList, TargetList):
        print("\n=========================================")
        print("Calculations Input Layer => Hidden Layer")
        print("=========================================")

        # Calculate the input values of the Hidden Layer
        inputs = numpy.array(InputList, ndmin = 2).T
        targets = numpy.array(TargetList, ndmin = 2).T
        hiddenInputs = numpy.dot(self.WeightsInputToHidden, inputs)
        print("Weights: Input Layer => Hidden Layer\n" + str(self.WeightsInputToHidden))
        print("\nInput Values:\n" + str(inputs))
        print("\nInput Values Hidden Layer - after Matrix Multiplication: \n" + str(hiddenInputs))
        hiddenOutputs = self.activation_function(hiddenInputs)
        print("\nInput Values Hidden Layer - after Activation Function: \n" + str(hiddenOutputs))

        print("\n=========================================")
        print("Calculations Hidden Layer => Output Layer")
        print("=========================================")

        # Calculate the output values of the Hidden Layer
        finalInputs = numpy.dot(self.WeightsHiddenToOutput, hiddenOutputs)
        print("\nWeights: Hidden Layer => Output Layer\n" + str(self.WeightsHiddenToOutput))
        print("\nHidden Output Values:\n" + str(hiddenOutputs))
        print("\nOutput Values Hidden Layer - after Matrix Multiplication: \n" + str(finalInputs))
        finalOutputs = self.activation_function(finalInputs)
        print("\nOutput Values Hidden Layer - after Activation Function: \n" + str(finalOutputs))

        # Calculate the errors for both layers
        errorsOutputLayer = targets - finalOutputs
        errorsHiddenLayer = numpy.dot(self.WeightsHiddenToOutput.T, errorsOutputLayer)

        # Calculate the new weights from the Hidden Layer to the Output Layer
        self.WeightsHiddenToOutput += self.LearningRate * numpy.dot(
            (errorsOutputLayer * finalOutputs * (1.0 - finalOutputs)),
            numpy.transpose(hiddenOutputs))
        
        # Calculate the new weights from the Input Layer to the Hidden Layer
        self.WeightsInputToHidden += self.LearningRate * numpy.dot(
            (errorsHiddenLayer * hiddenOutputs * (1.0 - hiddenOutputs)),
            numpy.transpose(inputs))
        
        pass

    # Queries the Neural Network
    def Query(self, InputList):
        print("\n=========================================")
        print("Calculations Input Layer => Hidden Layer")
        print("=========================================")

        # Calculate the input values of the Hidden Layer
        inputs = numpy.array(InputList, ndmin = 2).T
        hiddenInputs = numpy.dot(self.WeightsInputToHidden, inputs)
        print("Weights: Input Layer => Hidden Layer\n" + str(self.WeightsInputToHidden))
        print("\nInput Values:\n" + str(inputs))
        print("\nInput Values Hidden Layer - after Matrix Multiplication: \n" + str(hiddenInputs))
        hiddenOutputs = self.activation_function(hiddenInputs)
        print("\nInput Values Hidden Layer - after Activation Function: \n" + str(hiddenOutputs))

        print("\n=========================================")
        print("Calculations Hidden Layer => Output Layer")
        print("=========================================")

        # Calculate the output values of the Hidden Layer
        finalInputs = numpy.dot(self.WeightsHiddenToOutput, hiddenOutputs)
        print("\nWeights: Hidden Layer => Output Layer\n" + str(self.WeightsHiddenToOutput))
        print("\nHidden Output Values:\n" + str(hiddenOutputs))
        print("\nOutput Values Hidden Layer - after Matrix Multiplication: \n" + str(finalInputs))
        finalOutputs = self.activation_function(finalInputs)
        print("\nOutput Values Hidden Layer - after Activation Function: \n" + str(finalOutputs))

        return finalOutputs
    
# Use the Neural Network
network = NeuralNetwork(3, 3, 3, 0.3)
network.Train([1.0, 0.5, -1.5], [1.0, 0.5, -1.5])
network.Query([1.0, 0.5, -1.5])


Calculations Input Layer => Hidden Layer
Weights: Input Layer => Hidden Layer
[[ 0.11675605 -0.17438314  0.33216924]
 [ 0.35793089  0.26870788 -0.10112231]
 [-0.21575715 -0.02326628  0.24061449]]

Input Values:
[[ 1. ]
 [ 0.5]
 [-1.5]]

Input Values Hidden Layer - after Matrix Multiplication: 
[[-0.46868937]
 [ 0.64396829]
 [-0.58831202]]

Input Values Hidden Layer - after Activation Function: 
[[0.3849265 ]
 [0.65564995]
 [0.35702225]]

Calculations Hidden Layer => Output Layer

Weights: Hidden Layer => Output Layer
[[-0.02421473 -0.0675996  -0.05297924]
 [ 0.2642521  -0.19879538 -0.27861261]
 [-0.08348912  0.43298536 -0.34356126]]

Hidden Output Values:
[[0.3849265 ]
 [0.65564995]
 [0.35702225]]

Output Values Hidden Layer - after Matrix Multiplication: 
[[-0.07255733]
 [-0.12809344]
 [ 0.12909064]]

Output Values Hidden Layer - after Activation Function: 
[[0.48186862]
 [0.46802035]
 [0.53222792]]

Calculations Input Layer => Hidden Layer
Weights: Input Layer => Hidden Layer
[[ 0.1

array([[0.48885481],
       [0.46899678],
       [0.49719761]])